/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { VifCards as VifCards } from './components/vif-cards/vif-cards';

interface HTMLVifCardsElement extends VifCards, HTMLElement {
}
declare var HTMLVifCardsElement: {
  prototype: HTMLVifCardsElement;
  new (): HTMLVifCardsElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "vif-cards": HTMLVifCardsElement;
  }
  interface ElementTagNameMap {
      "vif-cards": HTMLVifCardsElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "vif-cards": JSXElements.VifCardsAttributes;
      }
  }
  namespace JSXElements {
      export interface VifCardsAttributes extends HTMLAttributes {
        
      }
  }
}

import { VifDashboard as VifDashboard } from './components/vif-dashboard/vif-dashboard';

interface HTMLVifDashboardElement extends VifDashboard, HTMLElement {
}
declare var HTMLVifDashboardElement: {
  prototype: HTMLVifDashboardElement;
  new (): HTMLVifDashboardElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "vif-dashboard": HTMLVifDashboardElement;
  }
  interface ElementTagNameMap {
      "vif-dashboard": HTMLVifDashboardElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "vif-dashboard": JSXElements.VifDashboardAttributes;
      }
  }
  namespace JSXElements {
      export interface VifDashboardAttributes extends HTMLAttributes {
        
      }
  }
}

import { VifPlayer as VifPlayer } from './components/vif-player/vif-player';

interface HTMLVifPlayerElement extends VifPlayer, HTMLElement {
}
declare var HTMLVifPlayerElement: {
  prototype: HTMLVifPlayerElement;
  new (): HTMLVifPlayerElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "vif-player": HTMLVifPlayerElement;
  }
  interface ElementTagNameMap {
      "vif-player": HTMLVifPlayerElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "vif-player": JSXElements.VifPlayerAttributes;
      }
  }
  namespace JSXElements {
      export interface VifPlayerAttributes extends HTMLAttributes {
        
      }
  }
}

import { VifScore as VifScore } from './components/vif-score/vif-score';

interface HTMLVifScoreElement extends VifScore, HTMLElement {
}
declare var HTMLVifScoreElement: {
  prototype: HTMLVifScoreElement;
  new (): HTMLVifScoreElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "vif-score": HTMLVifScoreElement;
  }
  interface ElementTagNameMap {
      "vif-score": HTMLVifScoreElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "vif-score": JSXElements.VifScoreAttributes;
      }
  }
  namespace JSXElements {
      export interface VifScoreAttributes extends HTMLAttributes {
        
      }
  }
}

